{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: POSTGRES_PASSWORD
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: DB_PASSWORD
{{- end }}
