apiVersion: apps/v1
kind: Deployment
metadata:
  name: naijavote
  labels:
    app: naijavote
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: naijavote
  template:
    metadata:
      labels:
        app: naijavote
    spec:
      imagePullSecrets:
    {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: naijavote
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/naijavote
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.name }}
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.name }}
                  key: DB_PASSWORD
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
{{- toYaml .Values.resources.app | nindent 12 }}
