apiVersion: apps/v1
kind: Deployment
metadata:
  name: naijavote
  labels:
    app: naijavote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naijavote
  template:
    metadata:
      labels:
        app: naijavote
    spec:
      containers:
        - name: naijavote
          image: temiloluwaolorunfemi/naijavote:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/naijavote
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: naijavote-config
                  key: DB_USERNAME
                  optional: true
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: naijavote-config
                  key: DB_PASSWORD
                  optional: true
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
