apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: naijavote-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: naijavote-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: naijavote
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: naijavote
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: naijavote
        property: POSTGRES_PASSWORD
    - secretKey: DB_USERNAME
      remoteRef:
        key: naijavote
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: naijavote
        property: DB_PASSWORD
