apiVersion: v1
kind: Service
metadata:
  name: naijavote
  labels:
    app: naijavote
spec:
  type: ClusterIP
  selector:
    app: naijavote
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
